dockerize:
  image: docker
  services:
    - docker:dind
  script:
    - docker build --rm -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - master

test_dockerize:
  image: docker
  services:
    - docker:dind
  script:
    - docker build --rm -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
  except:
    - master